### ISSUE TITLE
Hassio support

### ISSUE THREAD

**Issue by 333ryan18** [craigjmidwinter/total-connect-client#23]
The latest release version 0.81.0 is giving me these errors:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/alarm_control_panel/totalconnect.py", line 98, in alarm_arm_home
    self._client.arm_stay()
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 112, in arm_stay
    self.arm(ARM_TYPE_STAY, location_name)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 133, in arm
    deviceId = self.get_security_panel_device_id(location)
  File "/usr/local/lib/python3.6/site-packages/total_connect_client/TotalConnectClient.py", line 154, in get_security_panel_device_id
    if device['DeviceName'] in self.VALID_DEVICES:
AttributeError: 'TotalConnectClient' object has no attribute 'VALID_DEVICES'`

Believe it has something to do with adding self to valid devices from this pr #18

**Comment by albertcard** [comment]
I've got this same issue. I'm using a [Honeywell Lynx Touch L5200](https://www.amazon.com/gp/product/B00LH18QDE/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1) and my device isn't part of the 'VALID DEVICES' listed. I'm running Home Assistant 0.81.2 (latest) and part of the requirement for that version to run is to have 'total_connect_client==0.20'. On the previous version of Home Assistant, I ran 'total_connect_client==0.17' without issue. 

With the new version of the Total Connect Client, you see the following variable [VALID_DEVICES]  and it's listed devices -- which appears new since Total Connect Client 0.19:

```
# vi TotalConnectClient.py

VALID_DEVICES = ['Security Panel',
                 'Security System',
                 'L5100-WiFi',
                 'Lynx Touch-WiFi',
                 'ILP5',
                 'LTE-XV',
                 'GSMX4G'
                 ]
```
I'm not sure if I can retrieve my valid device from some logs or via the python script otherwise I could manually test for a working solution.  I manually updated the python script with some additional variations of what I thought it might be but that didn't work:

```
VALID_DEVICES = ['Security Panel',
                 'Security System',
                 'L5100-WiFi',
                 'Lynx Touch-WiFi',
                 'ILP5',
                 'LTE-XV',
                 'GSMX4G',
                 'Lynx Touch L5200',
                 'L5200',
                 'L5200-WiFi',
                 'L5210',
                 ]
```

None of these work. So while HomeAssistant does recognize I have an alarm system, I can't interact with it. Is there any workaround or future update to add my device into the list or do I need to force Home Assistant to think TCT version 0.17 is the required version?

**Comment by 333ryan18** [comment]
I was able to add my device to the VALID_DEVICES list using the api available here: https://rs.alarmnet.com/TC21api/tc2.asmx?op=LoginAndGetSessionDetails
In the file that is returned the DeviceName is what needs to be added to the list.
In my case it looks like this:
` <DeviceName>GSMX4G</DeviceName>`
This still didn't fix being able to arm/disarm my system from Hassio. I do currently have another Pi setup running a Hassbian installation that works correctly.

**Comment by uchagani** [comment]
@craigjmidwinter this is caused by PR #18.  Adding `self` when calling `VALID_DEVICES` produces the below:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uchagani/dev/total-connect-client/total_connect_client/TotalConnectClient.py", line 276, in disarm
    deviceId = self.get_security_panel_device_id(location)
  File "/Users/uchagani/dev/total-connect-client/total_connect_client/TotalConnectClient.py", line 154, in get_security_panel_device_id
    if device['DeviceName'] in self.VALID_DEVICES:
AttributeError: 'TotalConnectClient' object has no attribute 'VALID_DEVICES'
```

**Comment by uchagani** [comment]
this will be fixed in the next release of home assistant.  PR has been opened for the new version.  https://github.com/home-assistant/home-assistant/pull/18344
